#!/bin/bash

HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH="${HERE}/usr/lib/:${LD_LIBRARY_PATH}"
export PATH="${HERE}/usr/bin:${PATH}"
if [ -z "$1" ] ; then
  exec "${HERE}/usr/bin/appimageupdategui"
else
  exec "${HERE}/usr/bin/appimageupdategui" "$1"
fi
