#!/bin/bash

# Put binary dependencies into the AppDirs depending on the architecture
# of the build host; this is supposed to be called by CMake automatically

HERE="$(dirname "$(readlink -f "${0}")")"
PARENT="${HERE}/.."
ARCH=$(uname -m)
BINARYDIR="${HERE}/${ARCH}"

if [ -e /usr/bin/pacman ] ; then

mkdir -p "${PARENT}"/AppImageAssistant.AppDir/usr/bin/ AppImageAssistant.AppDir/usr/lib/
cp "${BINARYDIR}"/xorriso "${PARENT}"/AppImageAssistant.AppDir/usr/bin/
cp "${BINARYDIR}"/libglade-2.0.so.0 "${BINARYDIR}"/libisofs.so.6 "${BINARYDIR}"/libisoburn.so.1 "${BINARYDIR}"/libburn.so.4 "${PARENT}"/AppImageAssistant.AppDir/usr/lib/
cp "${BINARYDIR}"/libjte* "${PARENT}"/AppImageAssistant.AppDir/usr/lib/ # Raspbian
mkdir -p "${PARENT}"/AppImageAssistant.AppDir/usr/share/pyshared/
cp "${BINARYDIR}"/unionfs-fuse "${PARENT}"/AppImageAssistant.AppDir/usr/bin/

mkdir -p "${PARENT}"/AppImageExtract.AppDir/usr/bin/ "${PARENT}"/AppImageExtract.AppDir/usr/lib/
cp "${BINARYDIR}"/xorriso "${PARENT}"/AppImageExtract.AppDir/usr/bin/
cp "${BINARYDIR}"/libisofs.so.6 "${BINARYDIR}"/libisoburn.so.1 "${BINARYDIR}"/libburn.so.4 "${PARENT}"/AppImageExtract.AppDir/usr/lib/

mkdir -p "${PARENT}"/AppImageMonitor.AppDir/usr/bin/ "${PARENT}"/AppImageMonitor.AppDir/usr/lib/
cp "${BINARYDIR}"/xorriso "${PARENT}"/AppImageMonitor.AppDir/usr/bin/
cp "${BINARYDIR}"/libisofs.so.6 "${BINARYDIR}"/libisoburn.so.1 "${BINARYDIR}"/libburn.so.4 "${PARENT}"/AppImageMonitor.AppDir/usr/lib/

    else

mkdir -p "${PARENT}"/AppImageAssistant.AppDir/usr/bin/ AppImageAssistant.AppDir/usr/lib/
cp "${BINARYDIR}"/xorriso "${PARENT}"/AppImageAssistant.AppDir/usr/bin/
cp "${BINARYDIR}"/libglade-2.0.so.0 "${BINARYDIR}"/libvte.so.9 "${BINARYDIR}"/libisofs.so.6 "${BINARYDIR}"/libisoburn.so.1 "${BINARYDIR}"/libburn.so.4 "${PARENT}"/AppImageAssistant.AppDir/usr/lib/
cp "${BINARYDIR}"/libjte* "${PARENT}"/AppImageAssistant.AppDir/usr/lib/ # Raspbian
mkdir -p "${PARENT}"/AppImageAssistant.AppDir/usr/share/pyshared/
cp "${BINARYDIR}"/vte.so "${PARENT}"/AppImageAssistant.AppDir/usr/share/pyshared/
cp "${BINARYDIR}"/unionfs-fuse "${PARENT}"/AppImageAssistant.AppDir/usr/bin/

mkdir -p "${PARENT}"/AppImageExtract.AppDir/usr/bin/ "${PARENT}"/AppImageExtract.AppDir/usr/lib/
cp "${BINARYDIR}"/xorriso "${PARENT}"/AppImageExtract.AppDir/usr/bin/
cp "${BINARYDIR}"/libisofs.so.6 "${BINARYDIR}"/libisoburn.so.1 "${BINARYDIR}"/libburn.so.4 "${PARENT}"/AppImageExtract.AppDir/usr/lib/

mkdir -p "${PARENT}"/AppImageMonitor.AppDir/usr/bin/ "${PARENT}"/AppImageMonitor.AppDir/usr/lib/
cp "${BINARYDIR}"/xorriso "${PARENT}"/AppImageMonitor.AppDir/usr/bin/
cp "${BINARYDIR}"/libisofs.so.6 "${BINARYDIR}"/libisoburn.so.1 "${BINARYDIR}"/libburn.so.4 "${PARENT}"/AppImageMonitor.AppDir/usr/lib/

    fi
  done
